name: recolf
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.1
  camera: ^0.9.4+19
  collection: ^1.15.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  go_router: ^3.1.0
  hive: ^2.2.0
  hive_flutter:
  path: ^1.8.0
  path_provider: ^2.0.9
  uuid: ^3.0.6
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  hive_generator:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf