name: recolf
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.1
  camera: ^0.9.4+19
  collection: ^1.15.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase_analytics: ^9.3.8
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.8.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_native_splash: ^2.2.9
  go_router: ^3.1.0
  hive: ^2.2.0
  hive_flutter:
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.9
  smooth_video_progress: ^0.0.4
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  video_trimmer: ^1.1.3

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  hive_generator:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_transparent.png
    - assets/translations/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttc

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#010101"
  image: "assets/images/splash.png"
  android_12:
    icon_background_color: "#010101"
    image: "assets/images/splash_android12.png"
